baseurl = "http://vladvasiliu.com/"
title = "vBlog"
#if not set copyright, default copyright template will be applied
copyright = "Copyright © 2016 Vlad Vasiliu; all rights reserved."

#[params]
#    highlight="Assign a syntax highlight style"

[author]
    name = "Vlad Vasiliu"
    github = "vladvasiliu"
    linkedin = "vlad-vasiliu-460b2b18"
    #facebook = "ID"
    gaID = "YOUR Google Analytics Tracking ID"
    twitter = "vvasiliu"
