baseURL = "https://vladvasiliu.com/"
title = "vBlog"
theme = "hugo-vitae"
copyright = "© 2022 Vlad Vasiliu"
languageCode = "en"

hasCJKLanguage = false
enableRobotsTXT = true


pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


#disqusShortname = "vladvasiliu"
#googleAnalytics = "UA-37751901-1"

[markup]
  [markup.highlight]
    codeFences = true
    noClasses = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    style = "monokai"

[params]
    subtitle = "Useful tips and snippets"

    # Optional 80x80 avatar image.
    avatar = "/img/avatar.png"

    # Content types to disable Disqus on.
    disableDisqusTypes = ["page"]

    # customCSS = "css/custom.css"  # Custom CSS applied to default styles.
    hideAuthor = true

[params.customjs]
# enable Javascript by setting to true
enabled = false

[params.comments]
# Enable Comments with "true"
enabled = false

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/post"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[params.social]]
  name = "Github"
  icon = "fab fa-github"
  url = "https://github.com/vladvasiliu"

[[params.social]]
  name = "Behance"
  icon = "fab fa-behance-square"
  url = "https://www.behance.net/vvasiliu"

[[params.social]]
  name = "Photography"
  icon = "fas fa-camera"
  url = "https://photo.vladvasiliu.com"
